In [189]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [191]:
data = pd.read_csv('house_data.csv')

In [193]:
data

Square_Footage  Num_Bedrooms  Num_Bathrooms  Year_Built  Lot_Size  \
0              1360             2              1        1981  0.599637   
1              4272             3              3        2016  4.753014   
2              3592             1              2        2016  3.634823   
3               966             1              2        1977  2.730667   
4              4926             2              1        1993  4.699073   
..              ...           ...            ...         ...       ...   
995            3261             4              1        1978  2.165110   
996            3179             1              2        1999  2.977123   
997            2606             4              2        1962  4.055067   
998            4723             5              2        1950  1.930921   
999            3268             4              2        1983  3.108790   

     Garage_Size  Neighborhood_Quality   House_Price  
0              0                     5  2.623829e+05  
1              1                     6  9.852609e+05  
2              0                     9  7.779774e+05  
3              1                     8  2.296989e+05  
4              0                     8  1.041741e+06  
..           ...                   ...           ...  
995            2                    10  7.014940e+05  
996            1                    10  6.837232e+05  
997            0                     2  5.720240e+05  
998            0                     7  9.648653e+05  
999            2                     2  7.425993e+05  

[1000 rows x 8 columns]

In [195]:
data.shape

(1000, 8)

In [197]:
data.head()

Square_Footage  Num_Bedrooms  Num_Bathrooms  Year_Built  Lot_Size  \
0            1360             2              1        1981  0.599637   
1            4272             3              3        2016  4.753014   
2            3592             1              2        2016  3.634823   
3             966             1              2        1977  2.730667   
4            4926             2              1        1993  4.699073   

   Garage_Size  Neighborhood_Quality   House_Price  
0            0                     5  2.623829e+05  
1            1                     6  9.852609e+05  
2            0                     9  7.779774e+05  
3            1                     8  2.296989e+05  
4            0                     8  1.041741e+06

In [199]:
data.tail()

Square_Footage  Num_Bedrooms  Num_Bathrooms  Year_Built  Lot_Size  \
995            3261             4              1        1978  2.165110   
996            3179             1              2        1999  2.977123   
997            2606             4              2        1962  4.055067   
998            4723             5              2        1950  1.930921   
999            3268             4              2        1983  3.108790   

     Garage_Size  Neighborhood_Quality    House_Price  
995            2                    10  701493.997069  
996            1                    10  683723.160704  
997            0                     2  572024.023634  
998            0                     7  964865.298639  
999            2                     2  742599.253332

In [203]:
data .describe()

Square_Footage  Num_Bedrooms  Num_Bathrooms   Year_Built     Lot_Size  \
count     1000.000000   1000.000000    1000.000000  1000.000000  1000.000000   
mean      2815.422000      2.990000       1.973000  1986.550000     2.778087   
std       1255.514921      1.427564       0.820332    20.632916     1.297903   
min        503.000000      1.000000       1.000000  1950.000000     0.506058   
25%       1749.500000      2.000000       1.000000  1969.000000     1.665946   
50%       2862.500000      3.000000       2.000000  1986.000000     2.809740   
75%       3849.500000      4.000000       3.000000  2004.250000     3.923317   
max       4999.000000      5.000000       3.000000  2022.000000     4.989303   

       Garage_Size  Neighborhood_Quality   House_Price  
count  1000.000000           1000.000000  1.000000e+03  
mean      1.022000              5.615000  6.188610e+05  
std       0.814973              2.887059  2.535681e+05  
min       0.000000              1.000000  1.116269e+05  
25%       0.000000              3.000000  4.016482e+05  
50%       1.000000              6.000000  6.282673e+05  
75%       2.000000              8.000000  8.271413e+05  
max       2.000000             10.000000  1.108237e+06

In [205]:
X = data.iloc[:, :-1].values  # All columns except the last one as features
y = data.iloc[:, -1].values   # Last column as the target (house price)


In [207]:
X

array([[1.36000000e+03, 2.00000000e+00, 1.00000000e+00, ...,
        5.99636640e-01, 0.00000000e+00, 5.00000000e+00],
       [4.27200000e+03, 3.00000000e+00, 3.00000000e+00, ...,
        4.75301385e+00, 1.00000000e+00, 6.00000000e+00],
       [3.59200000e+03, 1.00000000e+00, 2.00000000e+00, ...,
        3.63482272e+00, 0.00000000e+00, 9.00000000e+00],
       ...,
       [2.60600000e+03, 4.00000000e+00, 2.00000000e+00, ...,
        4.05506679e+00, 0.00000000e+00, 2.00000000e+00],
       [4.72300000e+03, 5.00000000e+00, 2.00000000e+00, ...,
        1.93092148e+00, 0.00000000e+00, 7.00000000e+00],
       [3.26800000e+03, 4.00000000e+00, 2.00000000e+00, ...,
        3.10879025e+00, 2.00000000e+00, 2.00000000e+00]])

In [209]:
y

array([ 262382.85227406,  985260.85449016,  777977.39011858,
        229698.91866361, 1041740.8589249 ,  879796.98352238,
        814427.86140899,  703413.11094468,  173875.03721558,
        504176.50605937,  335332.59275294,  635097.3959198 ,
        701133.80414712,  440726.28481629,  838719.4305035 ,
       1019192.6613592 ,  735850.81234216,  234261.64997474,
        396246.35888875,  672852.051981  ,  586086.56853891,
        740174.01465508,  370167.09090272,  530824.19677521,
        227515.30028798,  652166.14236589,  745670.63714772,
        513161.95119306,  432357.90610274,  434165.89663405,
        809686.20114353,  883819.09112186,  912468.04790467,
        281313.06144485,  705923.31489162,  656980.46042822,
        318266.27713209,  582468.79773652,  541967.63355925,
        188531.42345711,  565562.75043214,  697574.55566703,
        666733.47346169,  376388.02162864,  485380.95019563,
        735678.46220173,  296291.00100751, 1046315.89601366,
        187508.58531168,

In [211]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)


In [213]:
X_train.shape

(670, 7)

In [215]:
y_train.shape

(670,)

In [217]:
X_test.shape

(330, 7)

In [219]:
y_test.shape

(330,)

In [221]:
from sklearn.linear_model import LinearRegression  
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [223]:
y_pred = regressor.predict(X_test)


In [225]:
y_pred

array([ 785340.49689498,  798240.18151765,  917395.62445205,
        237557.63369398,  503932.32312119,  326619.784566  ,
        509585.59287639,  430510.8092421 ,  930848.5343361 ,
        416614.10692924,  906489.69919351,  275311.74987508,
        365961.48316351,  816883.10600945,  717374.1268215 ,
        856165.07211979,  994563.24072472,  241481.76396919,
        834876.77984207,  561676.45313831,  880435.05572361,
        417379.753187  ,  859897.86260454,  346530.34259584,
        357408.39243492,  174745.59462102,  723331.17324767,
        688454.99848725,  678247.38154409,  977591.16534303,
        414474.59876765,  530314.09922309,  824744.76583524,
        962996.19782597,  817158.65550462,  364863.46790806,
        711784.52397515,  731795.03658194,  891714.86851594,
        726240.85701889,  527357.30854592,  687609.67953828,
        444489.81396852,  630796.14397618,  703468.48068101,
        856320.66981655,  312681.57794273,  383412.47665494,
        786552.12087963,

In [227]:
from sklearn.metrics import mean_squared_error, r2_score

# Step 6: Evaluate Model Performance using MSE and R²
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"R² Score: {r2:.2f}")

Mean Squared Error (MSE): 95716548.63
R² Score: 1.00


In [229]:

# Optional: Display Actual vs Predicted Values
comparison = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print(comparison.head())


          Actual      Predicted
0  786584.610239  785340.496895
1  792681.518420  798240.181518
2  895675.554821  917395.624452
3  239234.574322  237557.633694
4  510968.140654  503932.323121


In [231]:
import pickle


In [233]:
# Save the model to a Pickle file using 'write binary' mode (wb)
with open('house_data.pkl', 'wb') as file:
    pickle.dump(regressor, file)

print("Model saved successfully in 'house_data'.pkl'")

Model saved successfully in 'house_data'.pkl'
